language: python

python:
  - 3.5
  - 3.6

install:
  - pip install -r requirements.txt

env:
  global:
  - secure: "qB82Xe5t7CaSmxYgSVTaB1OIgEnT+PC3E02nm2MIGH84pI17l8OZMEK0jN78r4rEWzKdIUygKn+uhH8NzL1SFWUVbpNPmQa9a9VLLhGwn7DaOYF9PF0Mlv+WMkI5HswSgtTaGb6x/wNg/mgUeMgsfPAryql9uJ1P4HA6dclUy22FSCRIugitaWla8JqUsRfJGf29gthThdsv991Vjoumg4KkUlVLhCqrs6MupUiX+HhNzJyJDYoMud/IcaNNWcg6xy4AUGtrhudv+LcG4WLr8EfBXfdKZmS3bReujOTWqyNo4k2K02wArpT7tRRlDcZPKmkpjCIYijD0fT9gtG30ZRoSO3ET8LfR1m8Y4Y4FHgSgDVDWUCNUAC/ZbvA6NIdNEKMLmpv5YWvCEMfOfpxvlTYG/tNBEfLhOi6ZzPh5zAW+C5+CiDmBHlQ+1et8nR4fhwCPX80D6Y03US2V1I8ED2j3qbqtf7lcYqGHcQ3PCwOqVMH8AdjlvFUFGxU0Ps3//rcz/gjaCjRTC3xFDC2/+1gO0AeuEuU4YEO0nlsOT6dM+xX2kdXFIgEpxMmDhCFEO9cZ9FW5ONRZxdn2iuS3uSY7cmPjv9MgibomSpRp7ylz5x83ZPxL9p8w+WuwJ9kI/w2EQkKsq3TBuQxm98yVteJpfd/GHEKv7XVscCkR9xk="
  - GH_USER_NAME: "chaostoolkit-ci"
  - secure: "xR2xoqHvGaGcs0Y+r82c2nBWWBTodNr3Otvu8IlgYrR261g3lY0Pbuur+NQitENSmjX0/CoqlYFHXcaS+a6ltKQtWQUFnt+um5sCjD4ls3mLa5alsyhz/Jw1IlVQvXyAvMv7BUHi4qcpk+bmi2uaVDCCigcZqBEp5HpUEwUwbOmvZe1j7rQraVxw7PAhfcar0IwvDApQTwo8NZRA1v7gA9M2teyXG0cExf8J1Pdv+bJw7bQlFmnwqG9p5hDaAFjJVl9F934GyIWNedl2MiKcOgGsSn865PG1I02kI/YIpq7Eggnj4VXVVoLIBzJNfbq8DFFkFfgDIujgKL4rHdgJ769syIT8PC7ViQnZwtHEWMkm4ZKtDuI5wIyupkGdIsgnAPRscN6ABhH+EYpmNb0Tz6B70zLJre9Skajtk/wqPJgTvZX6ahE5E/P1AHJqwwRVOLgqdEYx6eBRXxgRJFGDFxLs/qGWDK31+MIK4kh1lWdTDrui3c8nKStrJq6kM9RezUwPqeQfpJHHwZVzWjKr7ioL8mjszxSXSmLuqWjY3TBFmg+Ht6a2aVp/FlfbsaRDkf+GfS1ZN7tfgfh7Hd7oG36XXmMd8bO4X98uSP+WxFEUjp8ANpA5P7hN8KvUU+fzOrcvmV5dEGi2vngmUARbfzZlFs+gc8SCuU187ACXT50="
  - PYPI_USER_NAME: "chaostoolkit"

script: 
  - bash ci.bash

branches:
  except:
  - gh-pages